//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_HealthCheck {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblHealthID;
	protected global::System.Web.UI.WebControls.Label lblH_BodyTemperature;
	protected global::System.Web.UI.WebControls.Label lblH_PulseRate;
	protected global::System.Web.UI.WebControls.Label lblH_RespiratoryRate;
	protected global::System.Web.UI.WebControls.Label lblH_LeftDiastolic;
	protected global::System.Web.UI.WebControls.Label lblH_LeftSystolic;
	protected global::System.Web.UI.WebControls.Label lblH_RightDiastolic;
	protected global::System.Web.UI.WebControls.Label lblH_RightSystolic;
	protected global::System.Web.UI.WebControls.Label lblH_Height;
	protected global::System.Web.UI.WebControls.Label lblH_Weight;
	protected global::System.Web.UI.WebControls.Label lblH_Result;
	protected global::System.Web.UI.WebControls.Label lblH_Suggestion;
	protected global::System.Web.UI.WebControls.Label lblH_CheckTime;
	protected global::System.Web.UI.WebControls.Label lblH_MedicalInstitutions;
	protected global::System.Web.UI.WebControls.Label lblH_CheckUserID;


       
    }
}
