//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.extend_FamilyHistory {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblFamilyHistoryID;
	protected global::System.Web.UI.WebControls.Label lblFH_Type;
	protected global::System.Web.UI.WebControls.Label lblFH_Who;
	protected global::System.Web.UI.WebControls.Label lblFH_Note;
	protected global::System.Web.UI.WebControls.Label lblFH_UserID;


       
    }
}
