//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_Group {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtG_CName;
		protected global::System.Web.UI.WebControls.TextBox txtG_ParentID;
		protected global::System.Web.UI.WebControls.TextBox txtG_ShowOrder;
		protected global::System.Web.UI.WebControls.TextBox txtG_Level;
		protected global::System.Web.UI.WebControls.TextBox txtG_ChildCount;
		protected global::System.Web.UI.WebControls.TextBox txtG_Delete;
		protected global::System.Web.UI.WebControls.TextBox txtG_Type;
		protected global::System.Web.UI.WebControls.TextBox txtG_Code;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
