//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_Group {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblGroupID;
	protected global::System.Web.UI.WebControls.Label lblG_CName;
	protected global::System.Web.UI.WebControls.Label lblG_ParentID;
	protected global::System.Web.UI.WebControls.Label lblG_ShowOrder;
	protected global::System.Web.UI.WebControls.Label lblG_Level;
	protected global::System.Web.UI.WebControls.Label lblG_ChildCount;
	protected global::System.Web.UI.WebControls.Label lblG_Delete;
	protected global::System.Web.UI.WebControls.Label lblG_Type;
	protected global::System.Web.UI.WebControls.Label lblG_Code;


       
    }
}
