//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_HealthCheck {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblHealthID;
		protected global::System.Web.UI.WebControls.TextBox txtH_BodyTemperature;
		protected global::System.Web.UI.WebControls.TextBox txtH_PulseRate;
		protected global::System.Web.UI.WebControls.TextBox txtH_RespiratoryRate;
		protected global::System.Web.UI.WebControls.TextBox txtH_LeftDiastolic;
		protected global::System.Web.UI.WebControls.TextBox txtH_LeftSystolic;
		protected global::System.Web.UI.WebControls.TextBox txtH_RightDiastolic;
		protected global::System.Web.UI.WebControls.TextBox txtH_RightSystolic;
		protected global::System.Web.UI.WebControls.TextBox txtH_Height;
		protected global::System.Web.UI.WebControls.TextBox txtH_Weight;
		protected global::System.Web.UI.WebControls.TextBox txtH_Result;
		protected global::System.Web.UI.WebControls.TextBox txtH_Suggestion;
		protected global::System.Web.UI.WebControls.TextBox txtH_CheckTime;
		protected global::System.Web.UI.WebControls.TextBox txtH_MedicalInstitutions;
		protected global::System.Web.UI.WebControls.TextBox txtH_CheckUserID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
