//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_FamilyBaseInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblFimaryID;
		protected global::System.Web.UI.WebControls.TextBox txtF_FimaryCode;
		protected global::System.Web.UI.WebControls.TextBox txtF_UserID;
		protected global::System.Web.UI.WebControls.TextBox txtF_GroupID;
		protected global::System.Web.UI.WebControls.TextBox txtF_FimaryTel;
		protected global::System.Web.UI.WebControls.TextBox txtF_FimrayAddress;
		protected global::System.Web.UI.WebControls.TextBox txtF_HouseType;
		protected global::System.Web.UI.WebControls.TextBox txtF_HouseArea;
		protected global::System.Web.UI.WebControls.TextBox txtF_Ventilation;
		protected global::System.Web.UI.WebControls.TextBox txtF_Humidity;
		protected global::System.Web.UI.WebControls.TextBox txtF_Warm;
		protected global::System.Web.UI.WebControls.TextBox txtF_Lighting;
		protected global::System.Web.UI.WebControls.TextBox txtF_Sanitation;
		protected global::System.Web.UI.WebControls.TextBox txtF_Kitchen;
		protected global::System.Web.UI.WebControls.TextBox txtF_Fuel;
		protected global::System.Web.UI.WebControls.TextBox txtF_Water;
		protected global::System.Web.UI.WebControls.TextBox txtF_WasteDisposal;
		protected global::System.Web.UI.WebControls.TextBox txtF_LivestockBar;
		protected global::System.Web.UI.WebControls.TextBox txtF_ToiletType;
		protected global::System.Web.UI.WebControls.TextBox txtF_ResponsibilityUserID;
		protected global::System.Web.UI.WebControls.TextBox txtF_FillingUserID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
