//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_FamilyBaseInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblFimaryID;
	protected global::System.Web.UI.WebControls.Label lblF_FimaryCode;
	protected global::System.Web.UI.WebControls.Label lblF_UserID;
	protected global::System.Web.UI.WebControls.Label lblF_GroupID;
	protected global::System.Web.UI.WebControls.Label lblF_FimaryTel;
	protected global::System.Web.UI.WebControls.Label lblF_FimrayAddress;
	protected global::System.Web.UI.WebControls.Label lblF_HouseType;
	protected global::System.Web.UI.WebControls.Label lblF_HouseArea;
	protected global::System.Web.UI.WebControls.Label lblF_Ventilation;
	protected global::System.Web.UI.WebControls.Label lblF_Humidity;
	protected global::System.Web.UI.WebControls.Label lblF_Warm;
	protected global::System.Web.UI.WebControls.Label lblF_Lighting;
	protected global::System.Web.UI.WebControls.Label lblF_Sanitation;
	protected global::System.Web.UI.WebControls.Label lblF_Kitchen;
	protected global::System.Web.UI.WebControls.Label lblF_Fuel;
	protected global::System.Web.UI.WebControls.Label lblF_Water;
	protected global::System.Web.UI.WebControls.Label lblF_WasteDisposal;
	protected global::System.Web.UI.WebControls.Label lblF_LivestockBar;
	protected global::System.Web.UI.WebControls.Label lblF_ToiletType;
	protected global::System.Web.UI.WebControls.Label lblF_ResponsibilityUserID;
	protected global::System.Web.UI.WebControls.Label lblF_FillingUserID;


       
    }
}
