//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_UserBaseInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblU_Hometown;
	protected global::System.Web.UI.WebControls.Label lblU_CurrentAddress;
	protected global::System.Web.UI.WebControls.Label lblU_FilingUnits;
	protected global::System.Web.UI.WebControls.Label lblU_FilingUserID;
	protected global::System.Web.UI.WebControls.Label lblU_ResponsibilityUserID;
	protected global::System.Web.UI.WebControls.Label lblU_Committee;
	protected global::System.Web.UI.WebControls.Label lblU_FlingTime;
	protected global::System.Web.UI.WebControls.Label lblU_WorkingUnits;
	protected global::System.Web.UI.WebControls.Label lblU_WorkingContactName;
	protected global::System.Web.UI.WebControls.Label lblU_WorkingContactTel;
	protected global::System.Web.UI.WebControls.Label lblU_BloodType;
	protected global::System.Web.UI.WebControls.Label lblU_NationID;
	protected global::System.Web.UI.WebControls.Label lblU_MarriageStatus;
	protected global::System.Web.UI.WebControls.Label lblU_PermanentType;
	protected global::System.Web.UI.WebControls.Label lblU_Education;
	protected global::System.Web.UI.WebControls.Label lblU_PaymentType;
	protected global::System.Web.UI.WebControls.Label lblU_SocialNO;
	protected global::System.Web.UI.WebControls.Label lblU_MedicalNO;
	protected global::System.Web.UI.WebControls.Label lblU_FamilyCode;
	protected global::System.Web.UI.WebControls.Label lblU_RelationShip;
	protected global::System.Web.UI.WebControls.Label lblU_Status;


       
    }
}
