//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_Module {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblModuleID;
	protected global::System.Web.UI.WebControls.Label lblM_ApplicationID;
		protected global::System.Web.UI.WebControls.TextBox txtM_ParentID;
	protected global::System.Web.UI.WebControls.Label lblM_PageCode;
		protected global::System.Web.UI.WebControls.TextBox txtM_CName;
		protected global::System.Web.UI.WebControls.TextBox txtM_Directory;
		protected global::System.Web.UI.WebControls.TextBox txtM_OrderLevel;
		protected global::System.Web.UI.WebControls.TextBox txtM_IsSystem;
		protected global::System.Web.UI.WebControls.TextBox txtM_Close;
		protected global::System.Web.UI.WebControls.TextBox txtM_Icon;
		protected global::System.Web.UI.WebControls.TextBox txtM_Info;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
