//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_UserBaseInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
		protected global::System.Web.UI.WebControls.TextBox txtU_Hometown;
		protected global::System.Web.UI.WebControls.TextBox txtU_CurrentAddress;
		protected global::System.Web.UI.WebControls.TextBox txtU_FilingUnits;
		protected global::System.Web.UI.WebControls.TextBox txtU_FilingUserID;
		protected global::System.Web.UI.WebControls.TextBox txtU_ResponsibilityUserID;
		protected global::System.Web.UI.WebControls.TextBox txtU_Committee;
		protected global::System.Web.UI.WebControls.TextBox txtU_FlingTime;
		protected global::System.Web.UI.WebControls.TextBox txtU_WorkingUnits;
		protected global::System.Web.UI.WebControls.TextBox txtU_WorkingContactName;
		protected global::System.Web.UI.WebControls.TextBox txtU_WorkingContactTel;
		protected global::System.Web.UI.WebControls.TextBox txtU_BloodType;
		protected global::System.Web.UI.WebControls.TextBox txtU_NationID;
		protected global::System.Web.UI.WebControls.TextBox txtU_MarriageStatus;
		protected global::System.Web.UI.WebControls.TextBox txtU_PermanentType;
		protected global::System.Web.UI.WebControls.TextBox txtU_Education;
		protected global::System.Web.UI.WebControls.TextBox txtU_PaymentType;
		protected global::System.Web.UI.WebControls.TextBox txtU_SocialNO;
		protected global::System.Web.UI.WebControls.TextBox txtU_MedicalNO;
		protected global::System.Web.UI.WebControls.TextBox txtU_FamilyCode;
		protected global::System.Web.UI.WebControls.TextBox txtU_RelationShip;
		protected global::System.Web.UI.WebControls.TextBox txtU_Status;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
