//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_User {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
		protected global::System.Web.UI.WebControls.TextBox txtU_LoginName;
		protected global::System.Web.UI.WebControls.TextBox txtU_Password;
		protected global::System.Web.UI.WebControls.TextBox txtU_CName;
		protected global::System.Web.UI.WebControls.TextBox txtU_EName;
		protected global::System.Web.UI.WebControls.TextBox txtU_GroupID;
		protected global::System.Web.UI.WebControls.TextBox txtU_Email;
		protected global::System.Web.UI.WebControls.TextBox txtU_Type;
		protected global::System.Web.UI.WebControls.TextBox txtU_Status;
		protected global::System.Web.UI.WebControls.TextBox txtU_Licence;
		protected global::System.Web.UI.WebControls.TextBox txtU_Mac;
		protected global::System.Web.UI.WebControls.TextBox txtU_Remark;
		protected global::System.Web.UI.WebControls.TextBox txtU_IDCard;
		protected global::System.Web.UI.WebControls.TextBox txtU_Sex;
		protected global::System.Web.UI.WebControls.TextBox txtU_BirthDay;
		protected global::System.Web.UI.WebControls.TextBox txtU_MobileNo;
		protected global::System.Web.UI.WebControls.TextBox txtU_UserNO;
		protected global::System.Web.UI.WebControls.TextBox txtU_WorkStartDate;
		protected global::System.Web.UI.WebControls.TextBox txtU_WorkEndDate;
		protected global::System.Web.UI.WebControls.TextBox txtU_CompanyMail;
		protected global::System.Web.UI.WebControls.TextBox txtU_Title;
		protected global::System.Web.UI.WebControls.TextBox txtU_Extension;
		protected global::System.Web.UI.WebControls.TextBox txtU_HomeTel;
		protected global::System.Web.UI.WebControls.TextBox txtU_PhotoUrl;
		protected global::System.Web.UI.WebControls.TextBox txtU_DateTime;
		protected global::System.Web.UI.WebControls.TextBox txtU_LastIP;
		protected global::System.Web.UI.WebControls.TextBox txtU_LastDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtU_ExtendField;
		protected global::System.Web.UI.WebControls.TextBox txtU_LoginType;
		protected global::System.Web.UI.WebControls.TextBox txtU_HospitalGroupID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
