//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_Event {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtE_U_LoginName;
		protected global::System.Web.UI.WebControls.TextBox txtE_UserID;
		protected global::System.Web.UI.WebControls.TextBox txtE_DateTime;
		protected global::System.Web.UI.WebControls.TextBox txtE_ApplicationID;
		protected global::System.Web.UI.WebControls.TextBox txtE_A_AppName;
		protected global::System.Web.UI.WebControls.TextBox txtE_M_Name;
		protected global::System.Web.UI.WebControls.TextBox txtE_M_PageCode;
		protected global::System.Web.UI.WebControls.TextBox txtE_From;
		protected global::System.Web.UI.WebControls.TextBox txtE_Type;
		protected global::System.Web.UI.WebControls.TextBox txtE_IP;
		protected global::System.Web.UI.WebControls.TextBox txtE_Record;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
