//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_Event {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblEventID;
	protected global::System.Web.UI.WebControls.Label lblE_U_LoginName;
	protected global::System.Web.UI.WebControls.Label lblE_UserID;
	protected global::System.Web.UI.WebControls.Label lblE_DateTime;
	protected global::System.Web.UI.WebControls.Label lblE_ApplicationID;
	protected global::System.Web.UI.WebControls.Label lblE_A_AppName;
	protected global::System.Web.UI.WebControls.Label lblE_M_Name;
	protected global::System.Web.UI.WebControls.Label lblE_M_PageCode;
	protected global::System.Web.UI.WebControls.Label lblE_From;
	protected global::System.Web.UI.WebControls.Label lblE_Type;
	protected global::System.Web.UI.WebControls.Label lblE_IP;
	protected global::System.Web.UI.WebControls.Label lblE_Record;


       
    }
}
