//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_FieldValue {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblValueID;
		protected global::System.Web.UI.WebControls.TextBox txtV_F_Key;
		protected global::System.Web.UI.WebControls.TextBox txtV_Text;
		protected global::System.Web.UI.WebControls.TextBox txtV_Code;
		protected global::System.Web.UI.WebControls.TextBox txtV_ShowOrder;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
