//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_FimaryProblem {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtF_FimaryCode;
		protected global::System.Web.UI.WebControls.TextBox txtF_RecordTime;
		protected global::System.Web.UI.WebControls.TextBox txtF_StartTime;
		protected global::System.Web.UI.WebControls.TextBox txtF_endTime;
		protected global::System.Web.UI.WebControls.TextBox txtF_OverviewProblem;
		protected global::System.Web.UI.WebControls.TextBox txtF_DetailProblem;
		protected global::System.Web.UI.WebControls.TextBox txtF_FillingUserID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
