//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.record_FimaryProblem {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblF_FimaryCode;
	protected global::System.Web.UI.WebControls.Label lblF_RecordTime;
	protected global::System.Web.UI.WebControls.Label lblF_StartTime;
	protected global::System.Web.UI.WebControls.Label lblF_endTime;
	protected global::System.Web.UI.WebControls.Label lblF_OverviewProblem;
	protected global::System.Web.UI.WebControls.Label lblF_DetailProblem;
	protected global::System.Web.UI.WebControls.Label lblF_FillingUserID;


       
    }
}
