//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.supervision_Inspect {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblInspectID;
	protected global::System.Web.UI.WebControls.Label lblI_Location;
	protected global::System.Web.UI.WebControls.Label lblI_Type;
	protected global::System.Web.UI.WebControls.Label lblI_Date;
	protected global::System.Web.UI.WebControls.Label lblI_UserID;
	protected global::System.Web.UI.WebControls.Label lblI_Conent;
	protected global::System.Web.UI.WebControls.Label lblI_MainProblem;
	protected global::System.Web.UI.WebControls.Label lblI_Note;


       
    }
}
