//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.supervision_Inspect {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblInspectID;
		protected global::System.Web.UI.WebControls.TextBox txtI_Location;
		protected global::System.Web.UI.WebControls.TextBox txtI_Type;
		protected global::System.Web.UI.WebControls.TextBox txtI_Date;
		protected global::System.Web.UI.WebControls.TextBox txtI_UserID;
		protected global::System.Web.UI.WebControls.TextBox txtI_Conent;
		protected global::System.Web.UI.WebControls.TextBox txtI_MainProblem;
		protected global::System.Web.UI.WebControls.TextBox txtI_Note;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
