//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.AR_Announcement {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblAnnouncementID;
	protected global::System.Web.UI.WebControls.Label lblA_Title;
	protected global::System.Web.UI.WebControls.Label lblA_Content;
	protected global::System.Web.UI.WebControls.Label lblA_DateTime;
	protected global::System.Web.UI.WebControls.Label lblA_ResponsibilityUserID;
	protected global::System.Web.UI.WebControls.Label lblA_Type;


       
    }
}
