//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.education_Activity {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtA_DateTime;
		protected global::System.Web.UI.WebControls.TextBox txtA_Location;
		protected global::System.Web.UI.WebControls.TextBox txtA_Form;
		protected global::System.Web.UI.WebControls.TextBox txtA_Object;
		protected global::System.Web.UI.WebControls.TextBox txtA_Crowd;
		protected global::System.Web.UI.WebControls.TextBox txtA_Duration;
		protected global::System.Web.UI.WebControls.TextBox txtA_Organizers;
		protected global::System.Web.UI.WebControls.TextBox txtA_Partners;
		protected global::System.Web.UI.WebControls.TextBox txtA_Missionary;
		protected global::System.Web.UI.WebControls.TextBox txtA_Number;
		protected global::System.Web.UI.WebControls.TextBox txtA_Theme;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
