//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.education_Activity {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblActivityID;
	protected global::System.Web.UI.WebControls.Label lblA_DateTime;
	protected global::System.Web.UI.WebControls.Label lblA_Location;
	protected global::System.Web.UI.WebControls.Label lblA_Form;
	protected global::System.Web.UI.WebControls.Label lblA_Object;
	protected global::System.Web.UI.WebControls.Label lblA_Crowd;
	protected global::System.Web.UI.WebControls.Label lblA_Duration;
	protected global::System.Web.UI.WebControls.Label lblA_Organizers;
	protected global::System.Web.UI.WebControls.Label lblA_Partners;
	protected global::System.Web.UI.WebControls.Label lblA_Missionary;
	protected global::System.Web.UI.WebControls.Label lblA_Number;
	protected global::System.Web.UI.WebControls.Label lblA_Theme;


       
    }
}
