//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.sys_Online {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtO_SessionID;
		protected global::System.Web.UI.WebControls.TextBox txtO_UserName;
		protected global::System.Web.UI.WebControls.TextBox txtO_Ip;
		protected global::System.Web.UI.WebControls.TextBox txtO_LoginTime;
		protected global::System.Web.UI.WebControls.TextBox txtO_LastTime;
		protected global::System.Web.UI.WebControls.TextBox txtO_LastUrl;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
